### ISSUE TITLE
Jump in final residual

### ISSUE THREAD

**Issue by bensworth** [pyamg/pyamg#305] opened 2022-01-27 16:25 UTC
I am using my PyAMG fork because we haven't merged AIR/classical AMG yet to master and have an issue where my final residual with Krylov methods will often jump, e.g.,:
`[3.4659935723626183, ..., 9.256452070903889e-11, 4.731465515454317e-11, 2.281592666914811e-11, 1.075289040305692e-11, 5.79813106475958e-12, 0.0002523977544470091`
or
`[3.200714442989945, ..., 3.6994700883118674e-11, 2.041237787848636e-11, 1.1074794304944443e-11, 5.9070427810823384e-12, 1.4344741655307831e-05]`
Unfortunately I seem to be getting the solution of the final residual, not the best one. Have you guys seen anything like this?

Related, are you guys interested in merging any of the additions I implemented? There are a few open PRs that haven't been touched in years.

**Comment by lukeolson** [comment] 2022-01-27 16:29
on the first point... is your answer here helpful?  https://github.com/pyamg/pyamg/issues/204

You may want to merge main to your fork as we've updated a bunch of the stopping criteria in the krylov bits.  https://github.com/pyamg/pyamg/issues/203

**Comment by lukeolson** [comment] 2022-01-27 16:33
I've started to go back to peel apart some of the features in the old branches.  I'll add a list of items needed (like tests) and see where we're at.

**Comment by bensworth** [comment] 2022-01-27 17:27
Re first point, no for a few reasons I think anyways: (i) these are the residuals returned by the Krylov method, but somehow GMRES and FGMRES are computing a final residual >>> than the second to last residual, which as far as I know should never happen in a minimal residual method; also (ii) FGMRES is based on right preconditioning, and the corresponding residual should be of the original operator, not the preconditioned operator. 

Sounds good re branches and PRs. I remember there was talk about tests/code compatibility, etc., which I partially understand. But, I also feel like we have very untested CR and aSA in master. AIR and the classical coarsening/interps I added have been tested fairly extensively and are much more useful options to have IMO.

**Comment by jbschroder** [comment] 2022-01-27 18:24
Hi Guys,

Ben: A few questions.
- Can you halt your simulations one iteration earlier, and see if the
solution vector returned is significantly better?
- Also, are you using Householder or MGS GMRES?  If you don't do anything
specific, the default is Householder

https://github.com/pyamg/pyamg/blob/main/pyamg/krylov/_gmres_householder.py

I'm not sure what's going on, but let me try to work through it.  If we
look at that code, the residuals are mostly created in the inner loop, and
in line 287, the last entry in the "g" vector is used to get the residual.
Now that "g" vector is the vector when solving the Hessenberg system (where
I think the last row is zero, so you can't solve for the last entry in g,
from what I just re-read in Saad 6.5.3 second edition)
H y = g
where H is of size niter+1 X niter.  Saad recommends this as a cheaper way
to get the residual.  But, the last residual is computed _directly_ from ||
M(b-Ax) ||_2.  So, I'm wondering if there is some kind of weird numerical
effect (like say if your precon is near singular) that messes with the
cheap residual norms as measured by just the last entry in "g".

To check this, you could pass a callback() function to GMRES that computes
it's own residual, i.e., callback(x) -->  || b - A*x ||_2  or || M(b - A*x)
||_2
That would be a good experiment to try out.

Regarding the other point, I completely agree that our CR and aSA aren't
ready for "prime-time" (in large part because CR and aSA aren't ready for
prime-time and these implementations mostly follow the papers).  But, we
have unit tests for both of these capabilities, that check and make sure
nothing breaks in these routines from one commit to the next.  I agree that
your AIR solver and interpolation routines have been thoroughly tested by
you and others over the years in your research and should definitely go
into PyAMG main branch.

I think the point here is that for the library release of PyAMG, we need
some unit tests to check that all the basic functionality of PyAMG still
works (and hasn't been inadvertently changed).  I've been thinking that
this is something that Ahsan could look at.  He needs more practice with
Python.  Let me know what you think!

Cheers,

Jacob

**Comment by lukeolson** [comment] 2022-01-27 18:48
@bensworth can you post an example (code)?  I'll see if I can reproduce...

**Comment by bensworth** [comment] 2022-01-27 21:21
Thanks @jbschroder, good ideas. I paused it a few iterations earlier and have the same behavior so probably something unstable numerically. Callback operates on the norm of the residual as computed form Householder, so that doesn't seem like it will help. Also, is there a way to pass any arguments to inner Krylov methods? There are some other options like restart and orthogonalization that may help debug what's going on, but not clear they can be accessed from multilevel.py

**Comment by lukeolson** [comment] 2022-01-27 21:37
The callbacks should now work on `x`: 
https://github.com/pyamg/pyamg/blob/main/pyamg/krylov/_fgmres.py#L290
versus
https://github.com/bensworth/pyamg/blob/master/pyamg/krylov/_fgmres.py#L315

**Comment by jbschroder** [comment] 2022-01-27 21:38
Thanks for the updates!  That does sound like a numerical stability issue (most likely).  

In my pyamg version, my Householder callback operates on "x".   See my screen shot below.  Maybe you want to copy over the gmres_householder from PyAMG head?  That way you could track the residual norm manually with something like callback(x) --> ||b - Ax||_2

For all the GMRES bells-n-whistles, you can call GMRES directly from pyamg.krylov, and pass in 
M = solver.aspreconditioner()

But, the reorthogonalization should only be available with MGS.  If you are using MGS, try to switch to Householder, that should be more stable.

![Screen Shot 2022-01-27 at 2 26 57 PM](https://user-images.githubusercontent.com/4768739/151446519-f90882f6-748f-4fb7-a4ac-93ecc719a8d9.png)

**Comment by jbschroder** [comment] 2022-01-27 21:38
Woops, and it looks like Luke just answered too about the callbacks!

**Comment by jbschroder** [comment] 2022-01-27 21:44
So, you could try something like this (though it measures true residual with callback -- you could insert a multiply by M in callback for the preconditioned residual)
![Screen Shot 2022-01-27 at 2 43 43 PM](https://user-images.githubusercontent.com/4768739/151448782-ef81bbc8-6f03-4c39-8738-7c27c6b8f26e.png)

**Comment by lukeolson** [comment] 2022-02-07 00:53
Following up here.  Can we get a MWE to work with to help chase down the issue?

**Comment by bensworth** [comment] 2022-02-18 16:53
Hi Jacob, not really; the problem I was working with I think was yielding an almost singular preconditioner. It's also not a very good MWE because it's wrapped up in part of a block preconditioning with custom Firedrake/petsc interface. Think @lukeolson 's student maybe had a similar problem with a simpler example?

**Comment by Alexey-Voronin** [comment] 2022-02-18 17:17
I observed similar behavior in the past #253, but I believe my issue was fixed in #279 -
https://github.com/pyamg/pyamg/blob/6e0507c1b2f5686f2b71ca162fab76a50d5b07db/pyamg/krylov/_gmres_householder.py#L294-L299

**Comment by lukeolson** [comment] 2022-02-18 22:20
So there *can* be differences in the last residual and the inner residuals.  The inner residuals are computed from the last term of the Q * rhs in the least-squares solve:
https://en.wikipedia.org/wiki/Generalized_minimal_residual_method
<img width="554" alt="image" src="https://user-images.githubusercontent.com/1615863/154767700-025692b7-19e3-47e4-a04d-138661fcc26f.png">
The gamma_n.

The last residual is computed using `norm(b - A @ x)` where `x = x + Q @ y`.  Here's an example with
```python
    A = pyamg.gallery.poisson((100,100), format='csr')
    b = np.ones((A.shape[0],))
```
Notice the bump in the last step:
```
it    residual, gamma_n   residual, ||b-Ax||  difference
348:  0.000000000198636   0.000000000602023   0.000000000403387
349:  0.000000000173229   0.000000000592657   0.000000000419427
350:  0.000000000150319   0.000000000586629   0.000000000436310
351:  0.000000000131836   0.000000000580755   0.000000000448919
352:  0.000000000116605   0.000000000580436   0.000000000463831
353:  0.000000000103707   0.000000000577425   0.000000000473718
354:  0.000000000571932   0.000000000571932   0.000000000000000
```

This doesn't mean there isn't a bug, but it's unclear what to chase down at this point.

**Comment by lukeolson** [comment] 2022-02-18 22:24
Let's close for now.  But if there's a specific case or better checks, then let's reopen.

**Closed by lukeolson** 2022-02-18 22:24 UTC
