### ISSUE TITLE
No module named _amg_core

### ISSUE THREAD

**Issue by bastorer** [pyamg/pyamg#197] opened 2017-03-07 16:38 UTC
Hello,

I recently tried loading PyAMG and am running into problems with the import stage. It's been a while since I've used PyAMG, so I tried installing the latest version by cloning the repo but the problem persisted. I've previously used PyAMG successfully, but I'm not sure what the problem is now.

Any help would be greatly appreciated. 

The output from python is included below.

Some potentially useful things: 
* OS : OS X El Capitan, 10.11.4
* Python version 2.7.13 (also tried with 3.5.2)
* Installed package using `sudo python setup.py install` and received no errors as far as I can tell

~~~Python
Python 2.7.13 (default, Dec 18 2016, 05:35:35)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyamg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/__init__.py", line 61, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/classical/__init__.py", line 3, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/classical/classical.py", line 9, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/relaxation/__init__.py", line 5, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/relaxation/relaxation.py", line 10, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/util/__init__.py", line 6, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/util/utils.py", line 14, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/amg_core/__init__.py", line 3, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/amg_core/amg_core.py", line 25, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyamg/amg_core/amg_core.py", line 17, in swig_import_helper
ImportError: No module named _amg_core

**Comment by lukeolson** [comment] 2017-03-28 17:34
I'm unable to reproduce this, but it seems like you might have a path issue.  How did you install numpy+scipy and where do these packages live?  in `"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/"`?

**Comment by lukeolson** [comment] 2017-05-23 14:24
closing for now...  let's reopen if it remains an issue.

**Comment by lukeolson** [comment] 2017-06-03 16:37
Reopening.  I can reproduce this now.

**Comment by lukeolson** [comment] 2017-10-06 15:19
Can't reproduce now.  If there are steps that lead to this, then we'll reopen.

**Closed by lukeolson** 2017-10-06 15:19 UTC
