### ISSUE TITLE
pyAMG leaking memory

### ISSUE THREAD

**Issue by dionhaefner** [pyamg/pyamg#198] opened 2017-05-18 14:09 UTC
Test script:

```python
import numpy as np
import pyamg

stencil = [ [-1,-1,-1],[-1,8,-1],[-1,-1,-1] ]
A = pyamg.gallery.stencil_grid(stencil, (100,100), dtype=float, format='csr')
near_null_space = np.ones(A.shape[0])
ml = pyamg.smoothed_aggregation_solver(A, near_null_space[:, np.newaxis])

for _ in range(10000):
    rhs = np.random.randn(A.shape[0])
    x0 = np.random.randn(A.shape[0])
    solution = ml.solve(b=rhs.flatten(), x0=x0.flatten(), accel="bicgstab")
```

Running ``mprof python test.py`` and ``mprof plot`` reveals a steady rise of memory consumption:

![memoryleak](https://cloud.githubusercontent.com/assets/11994217/26206073/0f5dfe90-3be4-11e7-9028-0568b52b5e62.png)

Output of ``pip freeze``:
```
appdirs==1.4.3
cycler==0.10.0
functools32==3.2.3.post2
matplotlib==2.0.2
memory-profiler==0.47
numpy==1.12.1
packaging==16.8
pkg-resources==0.0.0
psutil==5.2.2
py==1.4.33
pyamg==3.2.1
pyparsing==2.2.0
pytest==3.0.7
python-dateutil==2.6.0
pytz==2017.2
scipy==0.19.0
six==1.10.0
subprocess32==3.2.7
```

Output of ``python --version``:

```
Python 2.7.12
```

I am running on Ubuntu 17.04.

**Comment by lukeolson** [comment] 2017-05-23 14:27
Thanks for this.  I can reproduce in Python 3 as well.  I've narrow the issue to relaxation.  If I leave out pre/post smoothing then the memory stays bounded:

![figure_1](https://cloud.githubusercontent.com/assets/1615863/26358993/df03e64c-3f99-11e7-82a3-af0acfb8f5f5.png)

In fact, just adding `gauss_seidel` to the loop results in the same thing:

![figure_2](https://cloud.githubusercontent.com/assets/1615863/26359016/f3ed9f3a-3f99-11e7-9844-c0570a704472.png)

I'm using the following:
```python
from memory_profiler import profile

@profile
def prof():
    import numpy as np
    import pyamg

    stencil = [ [-1,-1,-1],[-1,8,-1],[-1,-1,-1] ]
    n = 25
    A = pyamg.gallery.stencil_grid(stencil, (n,n), dtype=float, format='csr')
    ml = pyamg.smoothed_aggregation_solver(A, max_levels=3)

    b = np.random.randn(A.shape[0])
    x = np.zeros(A.shape[0])

    for i in range(50000):
        print(i)
        #solution = ml.solve(b)
        pyamg.relaxation.relaxation.gauss_seidel(A, x, b)

if __name__ == '__main__':
    prof()
```

**Comment by lukeolson** [comment] 2017-05-23 14:28
It may be the way we're binding with SWIG.  I'll take a look.  I'm also looking at using pybind11 going forward, which may help.

**Comment by lukeolson** [comment] 2017-07-11 15:00
Update.  If I wrap gauss_seidel with pybind11, then the memory leak appears to be fixed.

![figure_1](https://user-images.githubusercontent.com/1615863/28074898-73ec432a-661f-11e7-8870-e4de4f1824e0.png)

In addition, it's slightly faster:

Pybind11:
66.8 ms ± 423 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

SWIG:
69.4 ms ± 645 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

It's unclear what is contributing to the memory leak with SWIG.  Looking at moving all of `amg_core` to pybind11 since it was relatively easy.

**Comment by dionhaefner** [comment] 2017-07-12 12:46
Thanks for the update. Looking forward to the fix!

**Comment by lukeolson** [comment] 2017-08-12 03:35
@dionhaefner can you try the `pybind11prototype` branch?  This avoids swig and it requires pybind11 but resolves the memory leak.

**Comment by dionhaefner** [comment] 2017-08-19 02:58
I am currently on vacation. Will try it out next week!

**Comment by dionhaefner** [comment] 2017-08-25 22:47
It still seems to leak a little, but nowhere near as much as before the fix:

![figure_1](https://user-images.githubusercontent.com/11994217/29735240-c7207204-89f7-11e7-8b10-21f02076bf03.png)

This is good enough for my purpose, so I would consider the problem fixed for now. Thanks!

**Comment by lukeolson** [comment] 2017-10-05 03:12
@dionhaefner would you mind posting your test script?  I agree it's minor but to "leak a little" is still worrisome :grin:

**Comment by dionhaefner** [comment] 2017-10-05 08:20
I used the script from my opening post, I think. If you can't reproduce it let me know and I will try again.

**Comment by lukeolson** [comment] 2017-10-05 16:29
Yes, I see something different:

![figure_2](https://user-images.githubusercontent.com/1615863/31238649-35601dc2-a9c0-11e7-998b-d86077beaa56.png)

As a start, try my script above which only calls `pyamg.relaxation.relaxation.gauss_seidel(A, x, b)`.  This may help isolate the issue.  I'll move to the solve call now...

**Comment by lukeolson** [comment] 2017-10-05 16:38
And if I run your top script ...
![figure_3](https://user-images.githubusercontent.com/1615863/31239105-a1ba3a42-a9c1-11e7-9581-f43a14325c95.png)

**Comment by lukeolson** [comment] 2017-10-05 16:40
@jbschroder can you test?

I pushed two scripts `testmemory.py` and `testmemory2.py` in the `amg_core` directory for lack of a better place.

Then
```
mprof run testmemory.py
mprof plot
```

**Comment by jbschroder** [comment] 2017-10-05 19:46
Hi All,

Here are my results.  Test_memory1 does not show a leak, but test_memory2
does show a small one (I think).

- Jacob

**Comment by jbschroder** [comment] 2017-10-05 20:06
![test_memory1](https://user-images.githubusercontent.com/4768739/31249888-e6eebd2a-a9cd-11e7-9018-509e354dbf73.png)
![test_memory2](https://user-images.githubusercontent.com/4768739/31249887-e6ecddf2-a9cd-11e7-9ec8-f2acd41d315d.png)

**Comment by jbschroder** [comment] 2017-10-05 20:09
cycler==0.10.0
matplotlib==2.0.2
memory-profiler==0.47
numpy==1.13.1
pyamg==3.3.0.dev0+bec23ff
pybind11==2.1.1
Pygments==2.2.0
pyparsing==2.2.0
pytest==3.2.1
python-dateutil==2.6.1
scipy==0.19.1

**Comment by dionhaefner** [comment] 2017-10-06 06:22
That's strange. Let me repeat my test during the weekend and then get back to you.

**Comment by lukeolson** [comment] 2017-10-06 11:44
Thanks.  Keep us posted.  I also added a `np.random.seed` so that we're all running the same experiment.

**Comment by dionhaefner** [comment] 2017-10-08 10:43
I can confirm @jbschroder's findings. ``testmemory2.py`` leaks a little, but nowhere as much as in my post from Aug 26, which is odd - maybe there was a leak in a dependency like NumPy at the time.

**Comment by lukeolson** [comment] 2018-07-31 00:32
Closing this issue in 851b7b8b0a2563a1ef24ce6474b22af33718acbd (probably should squash)

**Closed by lukeolson** 2018-07-31 00:32 UTC
