### ISSUE TITLE
Problem installing PyAMG on macOS Mojave

### ISSUE THREAD

**Issue by okrzysik** [pyamg/pyamg#240] opened 2019-02-20 20:48 UTC
When I try to install pyamg using:
%sudo python setup.py install

It gets to the line:
g++ -bundle -undefined dynamic_lookup -L/anaconda3/lib -arch x86_64 -L/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/pyamg/amg_core/evolution_strength_bind.o -o build/lib.macosx-10.7-x86_64-3.7/pyamg/amg_core/evolution_strength.cpython-37m-darwin.so
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]

Which produces the following error:
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1

Note: I can successfully install pyamg using:
%pip install pyamg
But I'd like to manually install using "%sudo python setup.py install" (such that I can install an alternative branch to the master).

I'm running macOS Mojave version 10.14.2 and Xcode version 10.1, and Python 3.7.0.

Thanks,
Oliver

**Comment by jbschroder** [comment] 2019-02-20 21:23
Hi Oliver,

Good to hear from you.  Are you installing from the "bleeding edge" head of
the repository?  I think that Luke may have already fixed this recently.

Cheers,

Jacob

**Comment by okrzysik** [comment] 2019-02-20 21:50
Hi Jacob,

Yes I believe so, I'm trying to install from the latest version of the master branch.

Thanks,
Oliver

**Comment by jbschroder** [comment] 2019-02-20 21:53
Hi Oliver,

Just to clarify, you mean that you're installing from
"git clone ..."
not a zip file?

Thanks,

Jacob

**Comment by okrzysik** [comment] 2019-02-20 21:56
Yes, that's correct.

Oliver

**Comment by lukeolson** [comment] 2019-02-20 22:02
For some reason it's not picking up the `libc++` flag here:
https://github.com/pyamg/pyamg/blob/master/setup.py#L177

What does this show?
```
python -c "import sys; print(sys.platform)"
```

**Comment by okrzysik** [comment] 2019-02-20 22:03
It says "darwin".

**Comment by lukeolson** [comment] 2019-02-20 22:05
This seems to be the issue:
https://github.com/pandas-dev/pandas/issues/23424#issuecomment-435612148

**Comment by lukeolson** [comment] 2019-02-20 22:12
I think I was attempting to fix that here:
https://github.com/pyamg/pyamg/commit/ba48f9283e28e0c4f44f04077734bd55d056af03#diff-2eeaed663bd0d25b7e608891384b7298

But I can't reproduce what you're seeing.  @jbschroder  do you have Mojave -- can you reproduce this?

**Comment by lukeolson** [comment] 2019-02-20 22:12
@okrzysik I'll keep digging.  If you have a `setup.py` fix let me know.

**Comment by jbschroder** [comment] 2019-02-20 22:26
I do not have Mojave, and I also use homebrew for all my compilers and
libs.

**Comment by isuruf** [comment] 2019-02-20 23:54
Pybind11 example setup.py is terrible. Fixed in https://github.com/pybind/python_example/pull/39. Can you copy that into pyamg setup.py and try again? (Unrelated: If you want MinGW support, copy https://github.com/pybind/python_example/pull/36 as well)

**Comment by okrzysik** [comment] 2019-02-21 04:37
@isuruf I copied the changes you'd made there into pyamg's setup.py and then pyamg installed, and all the tests in >>>pyamg.test() passed too. Thanks!

I'm not sure if it's any help, but I'm still getting the warning messages "warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use
      the libc++ standard library instead [-Wstdlibcxx-not-found]"

...
running build_ext
creating var
creating var/folders
creating var/folders/g8
creating var/folders/g8/nn6sy4t12yl_83mgwllct4y40000gq
creating var/folders/g8/nn6sy4t12yl_83mgwllct4y40000gq/T

gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.7m -I/anaconda3/lib/python3.7/site-packages/numpy/core/include -c /var/folders/g8/nn6sy4t12yl_83mgwllct4y40000gq/T/tmpie66kpr4.cpp -o var/folders/g8/nn6sy4t12yl_83mgwllct4y40000gq/T/tmpie66kpr4.o -std=c++14
<------- get warning here
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/include/python3.7m -I/anaconda3/lib/python3.7/site-packages/numpy/core/include -c /var/folders/g8/nn6sy4t12yl_83mgwllct4y40000gq/T/tmpnh83qhjj.cpp -o var/folders/g8/nn6sy4t12yl_83mgwllct4y40000gq/T/tmpnh83qhjj.o -fvisibility=hidden
<------- get warning here too

**Comment by isuruf** [comment] 2019-02-21 04:44
Hmm, can you send a PR with your changes? I can have a look

**Comment by isuruf** [comment] 2019-02-21 05:15
Ah, those warnings are from the temporary files compiled to detect flags. You can ignore those.

**Comment by okrzysik** [comment] 2019-02-21 05:17
Cool, thanks again!

**Comment by lukeolson** [comment] 2021-04-07 16:51
I think we resolved this.  But let me know if we need to reopen.

**Closed by lukeolson** 2021-04-07 16:51 UTC
