### ISSUE TITLE
Some potentially interesting benchmarks

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [pyamg/pyamg#220] opened 2018-03-04 07:14 UTC
Just ran into pyamg; great to see these complex algorithms be made available in such a neat package!

I started to try out pyamg in some of the more complex solves in my project, and these gave the following results; which perhaps could be improved upon by those with more knowhow of amg; and would perhaps be interesting additions to the examples/benchmarks.

The first thing I tried was a darcy-flow with high anisotropy; like groundwater that is free to move in some cracks but not in other places. [runnable example here](https://github.com/EelcoHoogendoorn/pycomplex/blob/master/examples/flow/darcy_flow.py). Even for modest grid sizes this solve takes several tens of seconds. This strikes me as the killer-app of amg; where it has the potential to even blow geometric multigrid out of the water.. But I havnt been able to realize anything but modest gains so far; about 20% over a minres solve. That strikes me as way below expectations. Maybe it is because I am trying to solve it as a mixed pressure-velocity formulation, and this complicates aggregation? (update; the difference is more like 40% on my 2-core last gen i5; as opposed to the 20% on my ancient 4-core i7. this leaves amg only 3-4 times slower on the highly anisotropic case compared to solving the same problem with purely isotropic coefficients. That isnt too bad; I suppose? Or could we do better with the right choice of parameters?)

The other thing I tried is more or less an exact copy-paste from the poisson eigenmodes example. [runnable example here](https://github.com/EelcoHoogendoorn/pycomplex/blob/master/examples/harmonics/spherical.py)
Here I am getting some decent gains for highly refined grids; but for refinement=6 grids and K=200 I get this error.

`numpy.linalg.linalg.LinAlgError: the leading minor of order 376 of 'b' is not positive definite. The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.
`

Note that there are perfectly well formed laplacian operators; L * D * L.T, with L full rank and D a positive diagonal). Seems like a numerical stability issue; Any ideas for how to mitigate/solve this?

**Comment by jbschroder** [comment] 2018-03-08 19:42
Hi Eelco,

Thank you for your interest in PyAMG! AMG is used a lot for groundwater
flow.  I would look at tuning in particular the strength of connection
parameter.  Also, how many iterations is AMG taking?

Regarding the eigenmode problem, it is typical that AMG only becomes faster
for larger problems.  At what size do you see a crossover and AMG becoming
faster than a sparse direct method?

- Jacob

**Comment by EelcoHoogendoorn** [comment] 2018-03-08 20:30
Hi Jacob,

I explored some settings wrt connection strength; but its been a while since I dug deep into AMG literature, so I was mostly just permuting things blindly. Are you perhaps aware of any good default settings for these type of problems?

The eigenmode problem does have a neat speedup; indeed more pronounced with larger grids, according to expectation. However, it is the error reported above that is spoiling the fun. I dont know about `the leading minor of order 376 of 'b'`; but the input matrix sure is positive definite.

**Comment by jbschroder** [comment] 2018-03-12 18:46
Hi Eelco,

Strength-of-connection usually varies in [0, 0.5], if you're using the
"classical" measure.  I would probably not use the symmetric measure.  You
could also try the "evolution" measure, which again has a tolerance that
varies between about [0, 0.5]. In both cases, a value of 0.25 or 0.33 is
typical.  There's also the choice of interpolation, which is probably most
important if you use the root_node_solver.  We can discuss this, too, if
you want.

I don't have a good idea about the eigenvalue error.  I see that you're
using (probably) the smoothed aggregation solver.  This should give you an
SPD preconditioner for a standard Laplacian (mathematically provable).
It's possible that LOBPCG needs to be tuned, that something is going on in
the eigensolver.  Hmmm....

- Jacob


On Thu, Mar 8, 2018 at 12:30 PM, Eelco Hoogendoorn <notifications@github.com

**Comment by EelcoHoogendoorn** [comment] 2018-03-16 08:56
Yeah... I think its some interaction between LOBPCG and the preconditioner. Without preconditioning I dont get these errors; and their onset can be delayed by tightening the tolerance in LOBPCG. So maybe the fault is entirely with LOBPCG but thats still a shame since its the only eigensolver in the python ecosystem that takes a preconditioner, that I am aware of. Either way its workable for my purposes now anyway.

Havnt gotten around to optimizing the anisotropic problem further, but its on my todo list.

**Comment by jbschroder** [comment] 2018-03-17 18:12
I'm glad that you've found a partial solution.  Let us know how they rest
of your project (s) go. -Jacob

On Mar 16, 2018 1:56 AM, "Eelco Hoogendoorn" <notifications@github.com>
wrote:

Yeah... I think its some interaction between LOBPCG and the preconditioner.
Without preconditioning I dont get these errors; and their onset can be
delayed by tightening the tolerance in LOBPCG. So maybe the fault is
entirely with LOBPCG but thats still a shame since its the only eigensolver
in the python ecosystem that takes a preconditioner, that I am aware of.
Either way its workable for my purposes now anyway.

Havnt gotten around to optimizing the anisotropic problem further, but its
on my todo list.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pyamg/pyamg/issues/220#issuecomment-373645943>, or mute
the thread

**Comment by EelcoHoogendoorn** [comment] 2018-03-20 19:35
Looking more into the eigensolver issues, im definitely inclined to put the blame on LOBPCG. It has some asserts with hardcoded tolerances; not a sign of the cleanest design.

monkey patching that away as such eliminates one failure mode; havnt seen this check catch any actually problematic cases yet:
```
from scipy.sparse.linalg.eigen.lobpcg import lobpcg
lobpcg._assert_symmetric = lambda x: None
```

Also, given a simple scalar laplacian with known nullspace, the numerical stability of LOBPCG improves substantially by passing in said nullspace as its constraint space; ie, Y=np.ones((n, 1))

So probably nothing to do with pyamg; perhaps this could be added to the pyamg example code, but either way thought id leave that here in case someone runs into the same thing in the future.

**Comment by EelcoHoogendoorn** [comment] 2018-03-22 09:27
On a related note; ive been generalizing the geometric multigrid code in the github repo linked above so I can make some apples-to-apples comparisons, and I get the same type of numerical stability issues when computing eigenvectors using that geometric multigrid implementation as I do using amg. 

Also, while I might be far from done optimizing, (so fwiw), minres+amg is currently about as fast or twice as fast as minres+geometric mg on a simple scalar poisson problem; so good job on that! Its interesting that minres+amg gains a lot over pure amg, whereas I have not been able to realize similar gains for adding minres to geometric mg. Is that to be expected?

**Comment by jbschroder** [comment] 2018-03-24 17:01
Hi Eelco,

Yes, thank you for writing this down for posterity. There's a good chance
that someone will come along with the same questions.  That is a shame that
the scipy LOBPCG isn't very robust.

Regarding geometric MG, we've written some of the computational kernels for
AMG in C++, so that could explain some performance differences.

For a standard Poisson problem, GMG and AMG should perform similarly, and
respond similarly to minres.  That is, they should both be similarly
"helped" by minres.  If the Poisson problem has any anisotropies,
coefficient jumps, etc., then GMG needs some changes to work well.

So...I'm not sure what's causing the difference between GMG and AMG
regarding minres.

As always, thanks for the update!

Jacob




On Thu, Mar 22, 2018 at 2:27 AM, Eelco Hoogendoorn <notifications@github.com

**Comment by EelcoHoogendoorn** [comment] 2018-03-24 19:02
Hi jacob,

wrt performance; my geometric mg code is formulated in terms of, and dominated by scipy.sparse.csr_matrix multiplications; which are implemented in cython. Depending on the low-level details of those cython/c++ implementations there might be some quite significant differences; but id hope the scipy implementation isnt too far from optimal.

I am considering a simple isotropic poisson problem here; in 2d, either as a regular grid or on the surface of a subdivided icosahedron. Running it on another laptop now and seeing quite some different and unexplained performance patters now again, so maybe too early to start drawing many conclusions from it. All comparisons are against smoothed aggregation with default settings.

Good to know I should expect similar performance of AMG vs MG on a 2d poisson problem; that will give me a baseline to calibrate how much effort i should spend optimizing my MG implementation. But to be honest, I doubt it is even worth it considering how well pyamg works; I was expecting quite some overhead for simple isotropic problems; but apparently not.

**Comment by EelcoHoogendoorn** [comment] 2018-03-27 08:24
Well, properly benchmarking things is hard... Turns out my test cases didnt control the spectral content of the right hand side very well, which was the cause of some of my confusion, as this can really give minres an advantage if there arnt a lot of high frequencies to deal with. With that taken care of, even my not-super tuned geometric mg is about twice as efficient as amg; for an isotropic 2d scalar laplacian. Which feels about right to me.

I feel ive made sense of the scalar problems now, but trying to solve vector-laplacian like problems opens up a whole new can of worms. amg slows down eigen computations for a 2d vector laplacian by about a factor two; but some preconditioning is required for numerical stability; without it i get really wonky eigenvectors. Solving a magnetostatics problem in terms of its H field is somehow made a lot worse by amg; both in terms of speed as well as numerical stability; with or without anisotropic coefficients. Geometric multigrid for the same problem is still a WIP; but solving these type of vector laplacian problems efficiently is what I am after, so I am curious how that will compare in the end. But right now I havnt really been able to get useful results from amg for the magnetostatic case at all

Hopefully I can wrap this up into a meaningfull benchmark suite when im done with it. When its all done, my package should be a really convenient way of setting up these kind of benchmarks.

Elastic Rayleigh wave on a disc found using amg preconditioned eigensolve; preconditioning is slower, but more stable
![frame_18](https://user-images.githubusercontent.com/1799429/37955054-c087ce62-31a7-11e8-9d8e-d6fc122b02a7.png)

Quarter of a permanent magnet with a slab of iron on top; solved using pure minres. Adding amg is slower and gives distorted results that do not respect the boundary conditions.
<img width="350" alt="screen shot 2018-03-27 at 10 11 53" src="https://user-images.githubusercontent.com/1799429/37955098-ed7b377e-31a7-11e8-8a32-522ea706ece6.png">

**Comment by jbschroder** [comment] 2018-03-27 20:43
Hi Eelco,

That is odd about the vector-Laplacians.  Have you tried "super-nodes",
that is storing the matrix as a BSR matrix?  This makes sense if you have 2
degrees of freedom at the same spatial location.  That would imply a BSR
matrix with 2x2 blocks.  If you have more degrees of freedom at the same
spatial location, the blocks just grow in size.  Passing in such a BSR
matrix to SA usually helps with interpolation, and lets you use block
relaxation.

Otherwise, the vector-Laplacian results are odd.  It makes me wonder if
there isn't something to tweak regarding strength of connection or some
other parameter.  If your GMG ends up working for these problems, then
there should be some way to get SA to work as well.

- Jacob

On Tue, Mar 27, 2018 at 1:25 AM, Eelco Hoogendoorn <notifications@github.com

**Comment by EelcoHoogendoorn** [comment] 2018-03-28 09:06
Hi Jacob,

No, there are no colocated degrees of freedom; the DOFs are fluxes through the quad boundaries.

I can see how this might be a challenge for AMG though; the resulting vector laplacian has a 5-point stencil; where horizontal edges only interact with their 4 adjacent horizontal edges and vice versa for the vertical ones; at least this is the situation in an isotropic interior. In the end the horizontal and vertical degrees of freedom are coupled locally, physically, but somehow this isnt particularly evident in the discretized equation. This means that if I add a horizontal component to the RHS, that error will have to propagate through the entire domain, 'reflect off' the boundary, until it can finally result in the vertical influence we know from physical experience this horizontal input will have locally. This sort of goes against multigrid philosophy, arguably.

To take a step back; I start with first order discrete operators representing
div(B) = 0
curl(B) = J
Both of which are very much local couplings between horizontal and vertical degrees of freedom; and then i form the normal equations of that system, giving me curl*curl+grad*div; something that resembles a laplace-beltrami operator, is guaranteed to be SPD, and indeed empirically has the 5-point stencil. I think that the fact that the horizontal and vertical degrees of freedom decouple has to do with the fact that forming our normal equations projects the equations and rhs onto the space of curl and divergence free fields; and for curl and divergence free fields they are decoupled; but until we have actually found such a solution this probably isnt the most useful way of thinking about our DOF's

The reason I went with that approach is because it makes minres happy; but forming the 5-point stencil by taking the normal equations is a solution-strategy, and nothing inherent to the physics of the problem. I think conceptually what might be needed is to feed some hypothetical multigrid algorithm the first order non-SPD equations, use those to reason about connection strength and aggregation, and internally smooth the equations in a least-square sense, effectively deferring the formation of the normal equations.

That way our residual vector to be mapped between multigrid levels would consist of divergence-free and irrotationality violations, and the local coupling between horizontal and vertical flux DOFs would be carried over by them.

Im probably reinventing the wheel here though; there must be some literature on the subject.

Eelco

**Comment by EelcoHoogendoorn** [comment] 2018-03-28 12:26
Ah; I hadnt tested this before, but amg and mg also slow down the lobpcg eigensolve of a scalar poisson problem, by about a similar factor two. So neither the vector laplacian or amg is special in that regard. Apparently eigen solving simply converges fine without preconditioning; although the preconditioning sure helps to converge to something sensible.

So that only leaves the failure to accelerate minres on a vectorial laplacian unexplained. Whatever spurious thing happens in the amg inversion of the vector laplacian apparently drops out of the eigen iteration, but not out of minres. Solving the magnetostatics using pure amg without minres is even wonkier; perhaps the visual result gives a clue to what goes wrong:

![screen shot 2018-03-28 at 14 19 03](https://user-images.githubusercontent.com/1799429/38028378-0db5905c-3293-11e8-8c54-d36a7d799144.png)

I also just noticed that for stokes flow (which has also has edge-based flux unknowns coupled through a laplacian, plus cell-based pressure unknowns), minres+amg works fine, but pure amg also gives spurious results.

I just realized that for all but the scalar poisson case, the solver isnt using a plausible near-nullspace; seeing as how im not giving it one, and the default is just a set of ones. Might that explain my troubles? Hopefully I can dig into that later today. If that turns out to be the case it is interesting how it hasnt been an issue for most use-cases.

**Comment by EelcoHoogendoorn** [comment] 2018-03-29 12:56
Ah I see there is quite some literature in recent years about asymmetric (algebraic) multigrid. These guys https://www.ricam.oeaw.ac.at/projects/AMG_AML/ seems to have been working on the same type of issues im running in to here.

**Comment by jbschroder** [comment] 2018-03-30 22:13
Hi Eelco,

You raise a good point about your near nullspace.  The default sets the
solver near nullspace parameter "B=ones((N,1))".

What is the near nullspace for your problem?  For just "curl-curl"
operators, this space is usually the space of all gradients.  But answering
this question is very important, and will guide your solver choices.

Regarding AMG for nonsymmetric problems, you can look at
https://github.com/pyamg/pyamg-examples/blob/master/Nonsymmetric/demo_recirc_flow.py
which highlights PyAMG options for nonsymmetric matrices.  This is
definitely still research, but these options have been fairly successful
for some nonsymmetric problems.

There's also a lot of other work out there on nonsymmetric AMG methods, as
you've already found :-)  There could even be some specialized solvers for
your problem type out there, but I don't know of any off the top of my head.

Cheers,

Jacob

On Thu, Mar 29, 2018 at 5:56 AM, Eelco Hoogendoorn <notifications@github.com

**Comment by EelcoHoogendoorn** [comment] 2018-03-31 07:13
Ah; when I said 'nonsymmetric' I meant 'nonsquare'. That seems to put you on even more experimental grounds, multigrid wise.

For a curl-curl operator, the true-nullspace would be the space of all gradients, right? So are you supposed to pass that entire massive things to AMG in that case? Either way that gradient space should not my problem. 

Should I pass AMG the null-space vectors associated with an infinite boundary-less domain? A scalar poisson also does not have ones in its nullspace for all boundary conditions; but thats still a fine default for the near-nullspace right? So for an elasticity problem I could pass it the rigid body modes; even if the domain is clamped down at the boundary?

**Comment by jbschroder** [comment] 2018-03-31 18:25
Hi Eelco,

Sorry for missing that fact!  Yes, nonsquare matrix equations with AMG is a
much less developed field.

For curl-curl operators, usually people use a specialized relaxation scheme
that projects out gradient-like functions.  If you run into this case, look
up Hiptmair-Xu relaxation.  Overlapping Schwarz can also work in this case.

As long as the number of near nullspace vectors don't change with problem
size (like the constant for Poisson, or rigid body modes for elasticity),
then it makes sense to pass them into smoothed-aggregation by setting the
"B" parameter.

Regarding the boundary conditions, those don't matter for the "B"
parameter.  The rigid-body-modes will still look like near nullspace
functions over the interior of the domain for classic elasticity problems.
PyAMG usually relaxes the "B" vectors, too, so that they are more accurate
near the boundaries.

Cheers,

Jacob

**Comment by lukeolson** [comment] 2018-07-31 00:47
One assumption is square matrices.  So I'm closing for now.  If there's a clear strategy for `m x n` matrices, let's reopen.

**Closed by lukeolson** 2018-07-31 00:47 UTC

**Comment by lobpcg** [comment] 2018-09-22 01:42
I would like to look into this. Preconditioning should make LOBPCG generally more robust, so there is something very strange here. If you still can reproduce the problem, could you please set  verbosityLevel=1 in LOBPCG so that it produces the screen output and copy/paste this output here?     
 
> Yeah... I think its some interaction between LOBPCG and the preconditioner. Without preconditioning I dont get these errors; and their onset can be delayed by tightening the tolerance in LOBPCG. So maybe the fault is entirely with LOBPCG but thats still a shame since its the only eigensolver in the python ecosystem that takes a preconditioner, that I am aware of. Either way its workable for my purposes now anyway.

**Comment by EelcoHoogendoorn** [comment] 2018-09-23 18:16
> I would like to look into this. Preconditioning should make LOBPCG generally more robust, so there is something very strange here. If you still can reproduce the problem, could you please set verbosityLevel=1 in LOBPCG so that it produces the screen output and copy/paste this output here?

Thanks for the support; I find I have a hard time recreating the original conditions; and I dont think its something in my code; but i didnt have my scipy version pinned; so that could be it?

To be exact; using (AMG) preconditioning is a massive help for my problem; without preconditioning I fail to get sensible eigenvectors for any interesting parameter configurations. The thing is, if I increase the stiffness of the problem, LOBPCG fails with a complaint about positive-definiteness; I suppose due to accumulation of numerical error? If instead I could get a sort of gracefull/gradual detoriation of numerical accuracy / convergence, that would be much preferred behavior; but this is not at all the case; the failure is quite sudden.

As for the problem being solved; it is a vector-laplacian with variable coefficients; or a discretization of the elasticity equations, with air-cell boundary conditions (first posted screenshot above is one of the correctly computed eigenmodes; a surface wave on a circular domain). I am absolutely certain that both A and B are symmetric by construction; so that cant be it.

[This example in this repo](https://github.com/EelcoHoogendoorn/pycomplex/blob/master/examples/elasticity/seismic.py) should be clonable, conda env create-able, and runnable as is, if that helps anything. Code is still very much in flux though so not sure how helpful it is to an outsider.

Here is the output with verbose mode:

```Solving generalized eigenvalue problem with preconditioning

matrix size 8320
block size 150

No constraints


iteration 0
current block size: 150
eigenvalue: [5.27789201e+08 6.67306692e+08 6.70598789e+08 6.74952591e+08
..snip...
 7.73881654e+10 8.26206997e+10]
iteration 1
current block size: 150
eigenvalue: [  40.48467372  110.42126142  251.18102075  278.75050771  296.41897675
..snip...
 270670.40404163 305841.22532902]
Traceback (most recent call last):
  File "/Users/eelco/development/hobby/pycomplex/examples/multigrid/equation.py", line 149, in eigen_basis
    v, V = scipy.sparse.linalg.lobpcg(A=A, B=B, X=X, tol=tol, M=M, Y=Y, largest=False, verbosityLevel=1)
  File "/Users/eelco/miniconda3/envs/pycomplex/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/lobpcg/lobpcg.py", line 490, in lobpcg
    _lambda, eigBlockVector = eigh(gramA, gramB, check_finite=False)
  File "/Users/eelco/miniconda3/envs/pycomplex/lib/python3.6/site-packages/scipy/linalg/decomp.py", line 493, in eigh
    " computed." % (info-b1.shape[0]))
numpy.linalg.linalg.LinAlgError: the leading minor of order 436 of 'b' is not positive definite. The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eelco/development/hobby/pycomplex/examples/elasticity/seismic.py", line 386, in <module>
    V, v = equation.eigen_basis(K=150, preconditioner='amg', tol=1e-11)
  File "/Users/eelco/development/hobby/pycomplex/examples/multigrid/equation.py", line 151, in eigen_basis
    v, V = scipy.sparse.linalg.lobpcg(A=A, B=B, X=X, tol=tol, M=M, largest=False, verbosityLevel=1)
  File "/Users/eelco/miniconda3/envs/pycomplex/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/lobpcg/lobpcg.py", line 490, in lobpcg
    _lambda, eigBlockVector = eigh(gramA, gramB, check_finite=False)
  File "/Users/eelco/miniconda3/envs/pycomplex/lib/python3.6/site-packages/scipy/linalg/decomp.py", line 493, in eigh
    " computed." % (info-b1.shape[0]))
numpy.linalg.linalg.LinAlgError: the leading minor of order 436 of 'b' is not positive definite. The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.
```

**Comment by lobpcg** [comment] 2018-09-24 01:09
Thanks for the output! Since LOBPCG fails on iteration 1, it cannot be due to "accumulation of numerical error" in the process of iterations. This is a very hard and rare failure. 

If you have complex-valued matrices, both A and B need to be Hermitian, not symmetric. Also, B must be positive definite. I assume that these conditions hold. If not, LOBPCG should normally fail.

What happens if you do not use preconditioning? If you use just block-size 1? 

How do you choose the initial X. What is Y? 

Could you please provide sample outputs for less stiff similar problems, where LOBPCG still works?

At the first iteration, the first iterative eigenvalue drops from the initial value e+08 to  e+01. That might be an indication that your problem is so ill-conditioned that it cannot be solved numerically in double precision... But please let me first know the answers to the questions above, if you could.

**Comment by lobpcg** [comment] 2018-09-24 01:17
The matrix size 8320 is small enough for you to compute all eigenpairs by using standard functions for dense matrices. Does this work? What are the exact eigenvalues, the smallest and the 150ths?

You can also check numerically for the purpose of debugging if your both matrices are real symmetric / complex Hermitian, and if B has all positive eigenvalues, indeed, as they should have.

**Comment by EelcoHoogendoorn** [comment] 2018-09-24 09:00
B is diagonal with positive entries; A is SPD by construction, as in L.T * D * L, with L full-rank.

Checking numerically, A already has some symmetry-violation due to accumulated numerical error in its formation though. However, ive never seen this been an issue in any numerical algorithm demanding symmetry.

Also, I tried an explicit A = (A + A.T) * 0.5 before calling lobpcg, and it does not change anything.

X is initialized with random numbers (Tried both rand and normal)
Y is left at null ('No constraints' as per above output)

Note that the failure, for a critical parameter range, is nondeterministic. For sufficiently nonstiff/stiff parameters it always (?) succeeds or fails.

My suspicion is that it is an interaction effect with the preconditioner. Note that I am using an AMG preconditioner. The documentation does not state what conditions the preconditioner should obey, but surely there are some. Maybe the AMG preconditioner does funny things with nulls-space components that are unexpected from the lobpcg perspective?

Emperically the AMG preconditioner still helps a ton for problems of sufficiently modest stiffness; but note that I started this thread because I found AMG doesnt exactly work great for vector-laplacians. That is, it utterly fails to find the correct solution; but apparently it still approximates the inverse sufficiently well; under some conditions?

**Comment by lobpcg** [comment] 2018-09-24 13:42
Where the "nulls-space components" come from if both A and B are SPD? 

The main implicit assumption is that the preconditioner is non-singular. The preconditioner is applied to a full-rank matrix made of residuals and must numerically preserve the full-rank. It may help the convergence if the preconditioner is fixed SPD.

Without getting into details, you can try just to apply the AMG preconditioner to A + alpha I or A + alpha B with some small fixed positive constant alpha. Increasing alpha gets you closer to stable but slower non-preconditioned case. 

Finally, since B is just diagonal, it should be beneficial to reduce the generalized eigenproblem  A - lambda B to the standard one for C A C where C is the inverse to the square root of B, by a change of variables. That should reduce the memory use and computations  inside LOBPCG and may increase the stability.

**Comment by EelcoHoogendoorn** [comment] 2018-09-24 14:40
I checked; this problem type can have null-space components given some type of boundary conditions; but indeed converting to dense and running eigsh reveals no such thing for this particular setup. Going over my old notes I see that i noticed null-space was an issue; for the case of a scalar potential with a gauge freedom; simply passing in the constant vector to LOBPCG as the constraint space seemed to solve that just fine. But its not the case for the particular failure we are looking at, which does not have a nullspace.

wrt generalized vs standard eigenproblems; what first got me to use LOBPCG was that it is the only eigensolver in the python ecosystem I could find that accepts a preconditioner, (and gave me stable low eigenvalues). This does not appear to have changed. For this number of unknowns direct methods might be more efficient; but this is just a pilot and ideally this could be taken to 3d and billions of unknowns

Applying a shift to the preconditioner sounds like something i should give a try. From what you are saying it sounds like it is indeed in interaction between the inability of the AMG preconditioner to do its black box magic on problems with edge-based unknowns (and freak out in the process), and the requirement of LOBPCG that the preconditioner preserves full rank. In that case the only takeaway here is that the scipy LOBPCG documentation could make these expectations more clear.

**Comment by lobpcg** [comment] 2018-09-24 16:49
After you reduce to the standard eigenproblem C A C , you still can use LOBPCG with AMG preconditioner for C A C , may be also + alpha I. You just save memory use and computations inside LOBPCG if B is None. 

LOBPCG is really the only widely available eigensolver, not just in Python, that allows direct preconditioning. This will not likely change, I guess, in any near future. 

Since there is no null-space in this case, AMG is supposed in theory to generate an SPD preconditioner, which is of course rank-preserving. So it still remains a mystery why LOBPCG fails in your case.  When you use eigsh, what are the eigenvalues with indexes 1, 150, 151, and the largest one? What happens if you run LOBPCG with block size 1 rather than 150?

May be this is an issue with AMG? To debug AMG, you can try to explicitly  generate the dense matrix M of the preconditioner, by applying the preconditioner function to all coordinate vectors one by one. Having the matrix M, you can check if it is SPD, as it should have, using direct eigensolvers. You can also look at the eigenvalues of the matrix MA or just calculate the norm of the difference matrix MA - I, which is supposed to be small. Another nice and simple test of AMG is to try solving a linear system Ax=b using a preconditioned conjugate gradient linear solve, and see it it works.

**Comment by EelcoHoogendoorn** [comment] 2018-09-24 19:38
I see; so what you are saying it that LOBPCG itself it more efficient if no B is passed in. Ill keep that in mind!

lambda[0]=2.8e-3 and lambda[150]=1.0e3; also the eigenvectors, when they get successfully computed, look physically entirely plausible; except for the last handful which sometimes violate some of the inherent symmetries of the setup, but that can be solved with more eigenvectors, or different tolerances I suppose. That is, when using preconditioning. Without preconditioning, from recollection, almost all eigenvectors always look like garbage. But again this is a very stiff problem so I am not inclined to blame LOBPCG for this.

As for what AMG should do in theory for this scenario I am not so sure even. I suspect the trouble is that the edge-based flux formulation breaks some assumptions in the way the smoother is constructed. 

WRT a simple test of AMG; that is what my magnetostatic screenshots above aim to illustrate. If (this particular implementation of) AMG cant solve my above magnetostatics problem, I suspect it will have qualitatively similar problems as a preconditioner for my elastics problem, which should be at least as problematic in terms of mathematical properties (could make this comparison more apples to apples but this was the easiest demonstration with the code I had). But indeed seeing the action of the preconditioner on a set of canonical basis vectors is a good idea too; hope to get around to trying that sometime soon.

As for what this means for LOBPCG; if LOBPCG was capable of internally detecting that the action of the preconditioner was at fault, that would be great for debugability! But from my limited understanding of the internal details, that likely isnt possible, especially without additional runtime cost.

**Comment by lobpcg** [comment] 2018-09-24 21:38
Thanks for more info! I am still puzzled. 

Could you please show the screen output, running with block size 1 with and without AMG?
And block size 150 without AMG?

**Comment by EelcoHoogendoorn** [comment] 2018-09-25 16:16
I must have changed some parameters somewhere; but this is what I am currently getting for a variety of block sizes:

Note that the dense-computed lowest eig equals 0.0028. Here is the value of the lowest eig for a range of different block sizes:

1: 0.03
10: 0.005-0.007 (minmax over a few runs)
50: 0.0028
100: LinAlgError in iteration 16

So with a block size of 10 even the first eigenmode is still rather dodgy, but with a block size of 50 it converges fine to the reference value. For some reason blocksize 100 already fails consistently now; but not in the first iteration.

This is all with AMG; ill try to get some numbers without later.

**Comment by EelcoHoogendoorn** [comment] 2018-09-25 16:19
Without preconditioner the smallest eigenvalue reported is 3363, blocksize=100.

Off by a few orders of magnitude...; but at least no complaints about positive definiteness; so that does point at the preconditioner as being the problem.

**Comment by lobpcg** [comment] 2018-09-25 17:17
That finally makes sense, thanks! LOBPCG converges monotonically, always giving upper bound for the smallest eigenvalues. Without preconditioning the convergence is extremely slow in your case, so probably impractical. 

Remember that you can and probably should adjust the default max number of iterations as well as the blocksize. Smaller eigenpairs within the block normally converge much faster, so you may also want to check the final values of the norms of the residuals, to see which eigenpairs have converged and discard those still inaccurate. 

Increasing the block size can make LOBPCG less numerically stable.  This is expected, especially when the eigenvalues within the block are different by many orders of magnitude, like in your case lambda[0]=2.8e-3 and lambda[150]=1.0e3. Make sure that you always use high quality normal random generator with zero mean for initial vectors, having no better approximations. 

For this problem, the blocksize 50 seems to be the best, with preconditioning. If you need more than 50 eigenvectors, e.g., 100, first compute 50 then run LOBPCG again with the blocksize 50, but with the previously computed 50 eigenvectors as constraints. You need to be careful choosing only well converged eigenvectors for constraints. 

So I think that there are no bugs to fix. It is just a poorly conditioned problem, as you have suggested from the beginning, where you need to be very careful choosing the combination of tolerance, max number of iterations, the blocksize, and preconditioning parameters to make LOBPCG to work. This implementation of LOBPCG is designed to be as fast as possible at the expense of not being ultimately stable in all cases, like a race car that you need to know how to drive... May be someone should also write a safe and always stable version of LOBPCG for large block sizes. 

Good luck and let me know if I could be of any further assistance!

**Comment by EelcoHoogendoorn** [comment] 2018-09-25 18:08
Thanks for the insight into LOBPCG's expected behavior. You use the phrase 'remember that', but LOBPCG hadnt been part of my linear-algebra repetoir so far (despite having implemented many iterative linalg algorithms many times), so I think this type of commentary would be great in the LOBPCG scipy docstring, since it is not at all obvious information to me. I was using random numbers from 0..1 previously most of the time, for starters!

So are you saying that you think the preconditioner indeed fails with a complaint about positive-definite-ness due to numerical precision? I am still very much open to the possibility that the preconditioner isnt quite doing what it should; but I guess I have to dive deeper into that to be sure.

**Comment by lobpcg** [comment] 2018-09-25 18:55
'Remember' I mean in your future use. 

LOBPCG has been written as a research code 17 years ago, but ended up being a production code in several libraries, for the lack of practical alternatives. It is surely not yet a standard part of numerical linear algebra curriculum. Its documentation  is lacking for a general user, indeed. 

Uniform random numbers from -0.5 to +0.5 should be OK. Vectors with components from 0..1 may be not enough random. 

In your reported case as far as I can see, LOBPCG fails on the first iteration at this line 490:

`# Solve the generalized eigenvalue problem.
_lambda, eigBlockVector = eigh(gramA, gramB, check_finite=False)`

probably because the matrix gramB, which in theory is supposed to be SPD by construction no matter what, and goes into Cholesky factorization, which fails, probably because the matrix is numerically singular. You can check this by running in debug mode, damping both matrices gramA and gramB and checking numerically if they are both SPD, as they should have in your case. If you check, please let me know what you find.

If you set in LOBPCG verbosityLevel > 10 it will dump all important intermediate vectors and matrices including gramA and gramB. If you do it, please upload them all somewhere for me to have a look at.

gramB is actually just the https://en.wikipedia.org/wiki/Gramian_matrix for a set of iterative vectors. It will be numerically singular if the set is not linearly independent. That may happen randomly due to a combination of factors, e.g.:
1) block size too large relative to the problem size,
2) initial approximations are funny,
3) the preconditioner does something unusual,
4) ill-conditioning of A and/or B.
